HotelManagement/HotelManagement/Models/RentForm.cs
using System.ComponentModel.DataAnnotations;

namespace HotelManagement.Models
{
	public class RentForm
	{
		[Key]
		public string RentFormID { get; set; }

		public string? BookingID { get; set; }

		[Required(ErrorMessage ="Room is not null!")]
		public string? RoomID { get; set; }

		[Required(ErrorMessage ="Staff is not null!")]
		public string? StaffID { get; set; }

		[Required(ErrorMessage ="Customer must be selected")]
		public string? CustomerID { get; set; }

		[DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
		public DateTime DateCreate { get; set; }

		[DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
		public DateTime DateCheckIn { get; set; }

		[DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
		public DateTime DateCheckOut { get; set; }
		public decimal Sale { get; set; }

		// Navigation properties
		public virtual Booking? Booking { get; set; } 
		public virtual Room? Room { get; set; }
		public virtual Staff? Staff { get; set; }
		public virtual Customer? Customer { get; set; }
	}
}

HotelManagement/HotelManagement/Areas/Admin/Controllers/RentController.cs
using HotelManagement.Data;
using HotelManagement.Models;
using HotelManagement.Models.Common;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace HotelManagement.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Route("Admin/Rent")]
	public class RentController : Controller
	{
		private HotelDbContext db;
		private int pageSize = 4;

		public RentController(HotelDbContext context)
		{
			this.db = context;
		}

		[Route("")]
		[Route("Index")]
		public IActionResult Index(string keyWord, int page = 1, string sortColumn = "DateCreate", bool isDesc = false)
		{
			// Get List 
			var listRentForm = db.RentForms.
							Include(r => r.Customer).
							Include(r => r.Staff).AsQueryable();

			// Search by KeyWord
			if (!String.IsNullOrEmpty(keyWord))
			{
				listRentForm = listRentForm.Where(r => r.RentFormID.Contains(keyWord) ||
														r.RoomID.Contains(keyWord) ||
														r.Staff.FirstName.Contains(keyWord) ||
														r.Staff.LastName.Contains(keyWord) ||
														r.Customer.LastName.Contains(keyWord) ||
														r.Customer.FirstName.Contains(keyWord));
			}

			// Sort by Date
			listRentForm = sortColumn switch
			{
				"DateCreate" => isDesc ? listRentForm.OrderByDescending(r => r.DateCreate) : listRentForm.OrderBy(r => r.DateCreate),
				"DateCheckIn" => isDesc ? listRentForm.OrderByDescending(r => r.DateCheckIn) : listRentForm.OrderBy(r => r.DateCheckIn),
				"DateCheckOut" => isDesc ? listRentForm.OrderByDescending(r => r.DateCheckOut) : listRentForm.OrderBy(r => r.DateCheckOut),
				_ => listRentForm
			};

			var currPageRental = listRentForm.Skip((page - 1) * pageSize).Take(pageSize).ToList();

			ViewBag.TotalPages = (int)Math.Ceiling(listRentForm.Count() / (double)pageSize);
			ViewBag.CurrentPage = page;
			ViewBag.SortColumn = sortColumn;
			ViewBag.IsDescending = isDesc;
			ViewBag.KeyWord = keyWord;

			return View(currPageRental);
		}

		[Route("Details")]
		public IActionResult Details(string id)
		{
            if (id == null)
            {
                return NotFound();
            }

            // Get information for Rent Form
            var rentForm = db.RentForms.
								Include(r => r.Customer).
								Include(r => r.Staff).
								Include(r => r.Room).
									ThenInclude(r => r.Category).
								Include(r => r.Room.RoomServices).
									ThenInclude(rs => rs.Service).
								FirstOrDefault(r => r.RentFormID == id);
            if (rentForm == null)
            {
                return NotFound();
            }
			ViewBag.RoomServices = rentForm.Room.RoomServices;

            return View(rentForm);
		}

		[HttpGet]
		[Route("Create")]
		public IActionResult Create()
		{
			var rooms = db.Rooms.Where(r => r.Status == "Vacant").
                                Include(r => r.Category).
                                ToList();
            var services = db.Services.ToList();
            var customers = db.Customers.Select(c => new
            {
                CustomerID = c.CustomerID,
                FullName = c.FirstName + " " + c.LastName,
                Membership = c.Membership
            }).ToList();

			// Generate RentForm ID
			string rentFormID = "RF00001";

			while (true)
			{
				int numberID = (int)new Random().NextInt64(100000);
				rentFormID = "RF" + numberID.ToString("D5");

				if (!ExistRentform(rentFormID))
					break;
			}

			// Get information for Rent Form
			ViewBag.Categories = new SelectList(db.Categories.ToList(), "CategoryID", "TypeName");
			ViewBag.BookingList = new SelectList(db.Bookings.ToList(), "BookingID", "BookingID");
            ViewBag.Staffs = new SelectList(db.Staffs.Select(s => new
            {
                StaffID = s.StaffID,
                FullName = s.FirstName + " " + s.LastName
            }).ToList(), "StaffID", "FullName");
            ViewBag.Customers = new SelectList(customers, "CustomerID", "FullName");
			ViewBag.RentFormID = rentFormID;
            ViewBag.Services = services;
            ViewBag.CustomerMemberShip = customers.ToDictionary(c => c.CustomerID, c => c.Membership);

			return View();
		}

		[HttpPost]
		[Route("Create")]
		[ValidateAntiForgeryToken]
		public IActionResult Create([Bind("RentFormID, BookingID, RoomID, StaffID, CustomerID, DateCreate, DateCheckIn, DateCheckOut, Sale")]RentForm rent, string[] SelectedServices)
        {
            if (ModelState.IsValid)
            {
				try
				{
					string newBookingID = "BK";
					while (db.Bookings.Any(b => b.BookingID == rent.BookingID))
					{
						newBookingID += new Random().NextInt64(100000).ToString("D5");
						rent.BookingID = newBookingID;
					}

					var room = db.Rooms.FirstOrDefault(r => r.RoomID == rent.RoomID);
					if (room != null)
					{
						room.Status = "Occupied";
						db.Entry(room).State = EntityState.Modified;
					}

					var bookingID = rent.BookingID;
					if (bookingID != null)
					{
						db.Add(new Booking 
						{ 
							BookingID = bookingID, 
							CustomerID = rent.CustomerID
						});
					}

					db.Add(rent);
					db.SaveChanges();

					return RedirectToAction(nameof(Index));
				}
				catch
				{
					if (!ExistRentform(rent.RentFormID))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
            }

            var rooms = db.Rooms.Where(r => r.Status == "Vacant").
								Include(r => r.Category).
								ToList();
			var customers = db.Customers.Select(c => new
			{
				CustomerID = c.CustomerID,
				FullName = c.FirstName + " " + c.LastName,
				Membership = c.Membership
			}).ToList();

			// Get information for Rent Form
			ViewBag.Categories = new SelectList(db.Categories.ToList(), "CategoryID", "TypeName");
            ViewBag.BookingList = new SelectList(db.Bookings.ToList(), "BookingID", "BookingID");
			ViewBag.Staffs = new SelectList(db.Staffs.Select(s => new
			{
				StaffID = s.StaffID,
				FullName = s.FirstName + " " + s.LastName
			}).ToList(), "StaffID", "FullName");
			ViewBag.Customers = new SelectList(db.Customers.Select(c => new
			{
				CustomerID = c.CustomerID,
				FullName = c.FirstName + " " + c.LastName
			}).ToList(), "CustomerID", "FullName");
            ViewBag.RentFormID = rent.RentFormID;
            ViewBag.Services = db.Services.ToList();
			ViewBag.CustomerMemberShip = customers.ToDictionary(c => c.CustomerID, c => c.Membership);

			return View();
		}

		/// <summary>
		/// Get List Room By Category
		/// </summary>
		/// <param name="categoryID"></param>
		/// <returns></returns>
		[Route("GetRoomByCategory")]
		public IActionResult GetRoomByCategory(string categoryID)
		{
			var rooms = db.Rooms
						.Where(r => r.CategoryID == categoryID && r.Status == "Vacant")
						.Select(r => new
						{
							RoomID = r.RoomID,
							RoomName = r.RoomID
						})
						.ToList();
			return Json(rooms);
		}

        [HttpGet]
		[Route("Edit")]
        public IActionResult Edit(string id)
        {
            // Check role
            var roleString = HttpContext.Session.GetString("Role");
            if (Enum.TryParse(roleString, out AccountType role) && role != AccountType.Admin)
            {
                // Not permission
                return RedirectToAction("AccessDenied", "Account");
            }

            if (id == null)
			{
				return NotFound();
			}

			// Get information for Rent Form
			var rentForm = db.RentForms.Where(r => r.RentFormID  == id).Include(r => r.Staff).Include(r => r.Customer).FirstOrDefault();

			if (rentForm == null)
			{
                return NotFound();
            }

            var rooms = db.Rooms.Where(r => r.Status == "Vacant").ToList();
            ViewBag.RoomVacant = new SelectList(rooms, "RoomID", "RoomID");
            return View(rentForm);
        }


		[HttpPost]
		[Route("Edit")]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(string id, [Bind("RentFormID, RoomID, StaffID, CustomerID, DateCreate, DateCheckIn, DateCheckOut, Sale")] RentForm rent)
		{
            if (id != rent.RentFormID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
				try
				{
					var existingRent = db.RentForms.Find(id);
					if (existingRent == null)
					{
						return NotFound();
					}
					if (rent.DateCheckOut.ToUniversalTime() <= DateTime.UtcNow)
					{
						var room = db.Rooms.FirstOrDefault(r => r.RoomID == existingRent.RoomID);
						if (room != null && room.Status == "Occupied")
						{
							room.Status = "Vacant";
							db.Entry(room).State = EntityState.Modified;
						}
					}
					else
					{
						// Change Status Room
						if (existingRent.RoomID != rent.RoomID)
						{
							var oldRoom = db.Rooms.FirstOrDefault(r => r.RoomID == existingRent.RoomID);

							// Update Status 
							if (oldRoom != null)
							{
								oldRoom.Status = "Vacant";
								db.Entry(oldRoom).State = EntityState.Modified;
							}

							var newRoom = db.Rooms.FirstOrDefault(r => r.RoomID == rent.RoomID);
							if (newRoom != null)
							{
								newRoom.Status = "Occupied";
								db.Entry(newRoom).State = EntityState.Modified;
							}
						}
						else
						{
							// Update Status Room if wrong
							var room = db.Rooms.FirstOrDefault(r => r.RoomID == existingRent.RoomID);
							if (room != null && room.Status == "Vacant")
							{
								room.Status = "Occupied";
								db.Entry(room).State = EntityState.Modified;
							}
						}
					}

					// Update RentForm
					existingRent.RoomID = rent.RoomID;
                    existingRent.DateCheckIn = rent.DateCheckIn;
                    existingRent.DateCheckOut = rent.DateCheckOut;
                    existingRent.Sale = rent.Sale;

                    db.Entry(existingRent).Property(r => r.RoomID).IsModified = true;
                    db.Entry(existingRent).Property(r => r.DateCheckIn).IsModified = true;

HotelManagement/HotelManagement/Areas/Admin/Views/Rent/Create.cshtml
@model HotelManagement.Models.RentForm

@{
	ViewData["Title"] = "Create";
	Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Create</h1>

<h4>RentForm</h4>
<hr />

<div class="row">
	<div class="col">
		<form asp-controller="Rent" asp-action="Create" method="post">
			<div asp-validation-summary="All" class="text-danger"></div>
			<div class="row">
				<div class="col-lg-6">
					<div class="card mb-4">
						<div class="card-body">
							<div class="form-group">
								<label asp-for="RentFormID" class="control-label" for="exampleFormControlReadonly"></label>
								<input asp-for="RentFormID" class="form-control" type="text" id="exampleFormControlReadonly" value="@ViewBag.RentFormID" readonly="">
							</div>
							<div class="form-group">
								<label asp-for="BookingID" class="control-label"></label>
								<select asp-for="BookingID" class="select2-single form-control" id="select2Single" asp-items="@ViewBag.BookingList"></select>
								<span asp-validation-for="BookingID" class="text-danger"></span>
							</div>
							<div class="form-group" id="simple-date1">
								<label asp-for="DateCreate" for="simpleDataInput"></label>
								<div class="input-group date">
									<div class="input-group-prepend">
										<span class="input-group-text"><i class="fas fa-calendar"></i></span>
									</div>
									<input type="text" class="form-control" asp-for="DateCreate" id="simpleDataInput" value="@DateTime.Now.ToShortDateString()">
								</div>
								<span asp-validation-for="DateCreate" class="text-danger"></span>
							</div>
							<div class="form-group" id="simple-date1">
								<label asp-for="DateCheckIn" for="simpleDataInput"></label>
								<div class="input-group date">
									<div class="input-group-prepend">
										<span class="input-group-text"><i class="fas fa-calendar"></i></span>
									</div>
									<input type="text" class="form-control" asp-for="DateCheckIn" id="simpleDataInput">
								</div>
								<span asp-validation-for="DateCheckIn" class="text-danger"></span>
							</div>
							<div class="form-group" id="simple-date1">
								<label asp-for="DateCheckOut" for="simpleDataInput"></label>
								<div class="input-group date">
									<div class="input-group-prepend">
										<span class="input-group-text"><i class="fas fa-calendar"></i></span>
									</div>
									<input type="text" class="form-control" asp-for="DateCheckOut" id="simpleDataInput">
								</div>
								<span asp-validation-for="DateCheckOut" class="text-danger"></span>
							</div>
							<div class="form-group">
								<label asp-for="Sale" class="control-label"></label>
								<input id="discountDisplay" asp-for="Sale" class="form-control" />
								<span asp-validation-for="Sale" class="text-danger"></span>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-6">
					<div class="card mb-4">
						<div class="card-body">
							<div class="form-group">
								<label asp-for="StaffID" class="control-label">Staff Create</label>
								<select asp-for="StaffID" class="select2-single form-control" id="select2Single" asp-items="@ViewBag.Staffs"></select>
								<span asp-validation-for="StaffID" class="text-danger"></span>
							</div>
							<div class="form-group">
								<label asp-for="CustomerID" class="control-label">Customer</label>
								<select id="customerSelect" asp-for="CustomerID" class="select2-single form-control" asp-items="@ViewBag.Customers">
									<option value="" disabled selected hidden>Select a customer</option>
								</select>
								<span asp-validation-for="CustomerID" class="text-danger"></span>
							</div>
							<a asp-controller="Customer" asp-action="Create" asp-route-navigate="true">Not member yet? Create</a>

						</div>
					</div>

					<div class="card mb-4">
						<div class="card-body">
							<div class="form-group">
								<label class="control-label">Category</label>
								<select id="categorySelect" class="select2-single form-control" asp-items="@ViewBag.Categories">
									<option value="" disabled selected hidden>Select Category</option>
								</select>
							</div>
							<div class="form-group">
								<label asp-for="RoomID" class="control-label">Room Vacant</label>
								<select id="roomSelect" asp-for="RoomID" class="select2-single form-control">
									<option value="" disabled selected hidden>Select Room</option>
								</select>
								<span asp-validation-for="RoomID" class="text-danger"></span>
							</div>
							<div>
								<label class="control-label">Service</label>
								@foreach (var service in ViewBag.Services)
								{
									<div class="form-check">
										<input class="form-check-input" type="checkbox" name="SelectedServices" value="@service.ServiceID" id="@service.ServiceID">
										<label class="form-check-label" for="@service.ServiceID">@service.ServiceName</label>
									</div>
								}
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="d-grid gap-2 d-md-block mt-3 mb-5">
				<input type="submit" class="btn btn-primary" value="Create" />
				<a class="btn btn-secondary" style="margin-left: 20px" asp-action="Index">Cancel</a>
			</div>
		</form>
	</div>
</div>

@section Styles {
	<link href="@(Url.Content("~/TemplateLayout/AdminPage/vendor/bootstrap-datepicker/css/bootstrap-datepicker.min.css"))" rel="stylesheet" />
	<link href="@(Url.Content("~/TemplateLayout/AdminPage/vendor/select2/dist/css/select2.min.css"))" rel="stylesheet" type="text/css">
}

@section Scripts {
	<script src="@(Url.Content("~/TemplateLayout/AdminPage/vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js"))"></script>
	<script src="@(Url.Content("~/TemplateLayout/AdminPage/vendor/select2/dist/js/select2.min.js"))"></script>
	<script>
		$(document).ready(function () {
			$('#simple-date1 .input-group.date').datepicker({
				format: 'mm/dd/yyyy',
				todayBtn: 'linked',
				todayHighlight: true,
				autoclose: true,
			});
		});

		const customerDiscounts = @Html.Raw(Json.Serialize(ViewBag.CustomerMemberShip));
		document.getElementById("customerSelect").addEventListener("change", function () {
			const selectedCustomerId = this.value;
			const memberShip = customerDiscounts[selectedCustomerId];
			let discount = 0;
			switch (memberShip) {
				case 0:
					discount = 0;
					break;
				case 1:
					discount = 0.1;
					break;
				case 2:
					discount = 0.15;
					break;
				case 3:
					discount = 0.2;
					break;
			}

			document.getElementById("discountDisplay").value = discount;
		});

		$('#categorySelect').change(function () {
			const categoryId = $(this).val();
			$.ajax({
				url: '/Admin/Rent/GetRoomByCategory',
				type: 'GET',
				data: { categoryId: categoryId },
				success: function (rooms) {
					const roomSelect = $('#roomSelect');
					roomSelect.empty().append('<option value="" disabled selected hidden>Select Room</option>');
					$.each(rooms, function (index, room) {
						roomSelect.append(`<option value="${room.roomID}">${room.roomName}</option>`);
					});
				},
				error: function () {
					alert('Failed to load rooms. Please try again.');
				}
			});
		});

	</script>
}

HotelManagement/HotelManagement/Areas/Admin/Views/Rent/Details.cshtml
@model HotelManagement.Models.RentForm

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Details</h1>

<div>
    <h4>RentForm</h4>
    <hr />
    <dl class="row">
        <div class="col">
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.RentFormID):
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.RentFormID)
            </dd>
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.BookingID):
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.BookingID)
            </dd>
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.RoomID):
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.RoomID)
            </dd>
            <dt class="col-sm-3">
                Staff Create:
            </dt>
            <dd class="col-sm-9">
                @Model.Staff?.FirstName @Model.Staff?.LastName
            </dd>
        </div>
        <div class="col">
            <dt class="col-sm-3">
                Customer:
            </dt>
            <dd class="col-sm-9">
                @Model.Customer?.FirstName @Model.Customer?.LastName
            </dd>
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.DateCreate):
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.DateCreate)
            </dd>
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.DateCheckIn):
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.DateCheckIn)
            </dd>
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.DateCheckOut):
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.DateCheckOut)
            </dd>
        </div>
    </dl>
</div>

<div class="card">
    <div class="table-responsive">
        <table class="table align-items-center table-flush">
            <thead class="thead-light">
                <tr>
                    <th>Room</th>
                    <th>Category</th>
                    <th>Service</th>
                    <th>Sale</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Html.DisplayFor(model => model.RoomID)</td>
                    <td>@Html.DisplayFor(model => model.Room.Category.TypeName)</td>
                    <td>
                        @foreach (var roomService in ViewBag.RoomServices)
                        {
                            <p>@roomService.Service.ServiceName</p>
                        }
                    </td>
                    <td>@Model.Sale.ToString("p2")</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<div class="d-grid gap-2 d-md-block mt-3 mb-5">
    <a class="btn btn-primary" asp-controller="Rent" asp-action="Edit" asp-route-id="@Model.RentFormID">Edit</a>
    <a class="btn btn-secondary" style="margin-left: 20px" asp-action="Index">Back To List</a>
</div>

HotelManagement/HotelManagement/Areas/Admin/Views/Rent/Edit.cshtml
@model HotelManagement.Models.RentForm

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Edit</h1>

<h4>RentForm</h4>
<hr />
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <form asp-controller="Rent" asp-action="Edit" asp-route-id ="@Model.RentFormID" method="post">
                    <input type="hidden" asp-for="RentFormID" />
                    <div class="form-group">
                        <label asp-for="RentFormID" class="control-label"></label>
                        <input asp-for="RentFormID" class="form-control" type="text" readonly="">
                    </div>
                    <div class="form-group">
                        <label asp-for="BookingID" class="control-label"></label>
                        <input asp-for="BookingID" class="form-control" readonly=""/>
                        <span asp-validation-for="BookingID" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="RoomID" class="control-label">Room</label>
                        <select asp-for="RoomID" class="select2-single form-control" id="select2Single" asp-items="@ViewBag.RoomVacant">
                            <option selected>@Model.RoomID</option>
                        </select>
                        <span asp-validation-for="RoomID" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="StaffID" class="control-label">Staff Create</label>
                        <input asp-for="StaffID" class="form-control" value="@Model.Staff?.FirstName @Model.Staff?.LastName" readonly="" />
                        <span asp-validation-for="StaffID" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CustomerID" class="control-label">Customer</label>
                        <input asp-for="CustomerID" class="form-control" value="@Model.Customer?.FirstName @Model.Customer?.LastName" readonly="" />
                        <span asp-validation-for="CustomerID" class="text-danger"></span>
                    </div>
                    <div class="form-group" id="simple-date1">
                        <label asp-for="DateCreate" for="simpleDataInput"></label>
                        <div class="input-group date">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-calendar"></i></span>
                            </div>
                            <input type="text" class="form-control" asp-for="DateCreate" id="simpleDataInput">
                        </div>
                        <span asp-validation-for="DateCreate" class="text-danger"></span>
                    </div>
                    <div class="form-group" id="simple-date1">
                        <label asp-for="DateCheckIn" for="simpleDataInput"></label>
                        <div class="input-group date">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-calendar"></i></span>
                            </div>
                            <input type="text" class="form-control" asp-for="DateCheckIn" id="simpleDataInput">
                        </div>
                        <span asp-validation-for="DateCheckIn" class="text-danger"></span>
                    </div>
                    <div class="form-group" id="simple-date1">
                        <label asp-for="DateCheckOut" for="simpleDataInput"></label>
                        <div class="input-group date">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-calendar"></i></span>
                            </div>
                            <input type="text" class="form-control" asp-for="DateCheckOut" id="simpleDataInput">
                        </div>
                        <span asp-validation-for="DateCheckOut" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Sale" class="control-label"></label>
                        <input asp-for="Sale" class="form-control" />
                        <span asp-validation-for="Sale" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                        <a class="btn btn-secondary" style="margin-left: 20px" asp-action="Index">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Styles {
    <link href="@(Url.Content("~/TemplateLayout/AdminPage/vendor/bootstrap-datepicker/css/bootstrap-datepicker.min.css"))" rel="stylesheet" />
}

@section Scripts {
    <script src="@(Url.Content("~/TemplateLayout/AdminPage/vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js"))"></script>
    <script>
        $(document).ready(function () {
            $('#simple-date1 .input-group.date').datepicker({
                format: 'mm/dd/yyyy',
                todayBtn: 'linked',
                todayHighlight: true,
                autoclose: true,
            });
        });
    </script>
}