HotelManagement/HotelManagement/Areas/Admin/Controllers/RoomsController.cs
using HotelManagement.Data;
using HotelManagement.Models;
using HotelManagement.Models.Common;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Net;

namespace HotelManagement.Areas.Admin.Controllers
{
    [Area("Admin")]
   
    [Route("Admin/Rooms")]
    public class RoomsController : Controller
    {
        private HotelDbContext db;

        public RoomsController(HotelDbContext db)
        {
            this.db = db;
        }

        [Route("")]
        [Route("Index")]
        public IActionResult Index(string SortColumn = "RoomID", string IconClass = "fa-sort-asc", int page = 1, string? CategoryID = null, string? Status = null)
        {
            var rooms = db.Rooms.Include(r => r.Category)
                                .Include(i => i.Images)
                                .AsQueryable();

            // Lưu giá trị của CategoryID và Status đã chọn vào ViewBag
            ViewBag.SelectedCategoryID = CategoryID;
            ViewBag.SelectedStatus = Status;

            // Lọc theo CategoryID và Status
            if (!string.IsNullOrEmpty(CategoryID))
            {
                rooms = rooms.Where(r => r.CategoryID == CategoryID);
            }

            if (!string.IsNullOrEmpty(Status))
            {
                rooms = rooms.Where(r => r.Status == Status);
            }

            // Sắp xếp
            ViewBag.SortColumn = SortColumn;
            ViewBag.IconClass = IconClass;
            rooms = SortRooms(rooms, SortColumn, IconClass);

            // Phân trang
            int NoOfRecordPerPage = 5;
            int NoOfPages = (int)Math.Ceiling((double)rooms.Count() / NoOfRecordPerPage);
            int NoOfRecordToSkip = (page - 1) * NoOfRecordPerPage;
            ViewBag.Page = page;
            ViewBag.NoOfPages = NoOfPages;
            rooms = rooms.Skip(NoOfRecordToSkip).Take(NoOfRecordPerPage);

            // Lấy danh sách Categories cho dropdown
            ViewBag.Categories = db.Categories.ToList();

            return View(rooms.ToList());
        }


        // Phương thức sắp xếp riêng, trả về IQueryable
        private IQueryable<Room> SortRooms(IQueryable<Room> rooms, string SortColumn, string IconClass)
        {
            if (SortColumn == "RoomID")
            {
                rooms = IconClass == "fa-sort-asc" ? rooms.OrderBy(r => r.RoomID) : rooms.OrderByDescending(r => r.RoomID);
            }
            else if (SortColumn == "Price")
            {
                rooms = IconClass == "fa-sort-asc" ? rooms.OrderBy(r => r.Category.Price) : rooms.OrderByDescending(r => r.Category.Price);
            }
            else if (SortColumn == "CategoryID")
            {
                rooms = IconClass == "fa-sort-asc" ? rooms.OrderBy(r => r.CategoryID) : rooms.OrderByDescending(r => r.CategoryID);
            }
            return rooms;
        }



        [Route("Details")]
        public IActionResult Details(string id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var room = db.Rooms.Include(c => c.Category)
                       .Include(i => i.Images)
                       .Include(s => s.RoomServices)
                       .ThenInclude(rs => rs.Service) // Include Service for RoomService
                       .Include(f => f.RentForms)
                       .FirstOrDefault(r => r.RoomID == id);
            if (room == null)
            {
                return NotFound();
            }
            return View(room); 
        }

        [HttpGet]
        [Route("Create")]
        public IActionResult Create()
        {
            // Check role
            var roleString = HttpContext.Session.GetString("Role");
            if (Enum.TryParse(roleString, out AccountType role) && role != AccountType.Admin)
            {
                // Not permission
                return RedirectToAction("AccessDenied", "Account");
            }

            var lastRoom = db.Rooms.OrderByDescending(r => r.RoomID).FirstOrDefault();
            string newRoomID = "R001";
            if(lastRoom != null)
            {
                int lastNumber = int.Parse(lastRoom.RoomID.Substring(1)) + 1;
                newRoomID = "R" + lastNumber.ToString("D3");
            }
            ViewBag.NewRoomID = newRoomID; 
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "TypeName");
            ViewBag.Services = db.Services.ToList(); // Lấy danh sách dịch vụ
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Create")]
        public IActionResult Create([Bind("RoomID,CategoryID, Status")] Room room, List<IFormFile> RoomImages, List<string> selectedServices)
        {
            if (ModelState.IsValid)
            {
                db.Rooms.Add(room);
                db.SaveChanges();

                var lastImage = db.Images.OrderByDescending(i => i.ImageID).FirstOrDefault();
                int lastNumber = lastImage != null ? int.Parse(lastImage.ImageID.Substring(3)) : 0;

                foreach (var imageFile in RoomImages)
                {
                    if (imageFile != null && imageFile.Length > 0)
                    {
                        string newImageID = "IMG" + (lastNumber + 1).ToString("D4");
                        lastNumber++;

                        var imagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", imageFile.FileName);
                        using (var stream = new FileStream(imagePath, FileMode.Create))
                        {
                            imageFile.CopyTo(stream);
                        }

                        var image = new Image
                        {
                            ImageID = newImageID,
                            RoomID = room.RoomID,
                            ImageUrl = "/img/" + imageFile.FileName
                        };

                        db.Images.Add(image);
                    }
                }

                // Lưu danh sách dịch vụ đã chọn
                foreach (var serviceId in selectedServices)
                {
                    var roomService = new RoomService
                    {
                        RoomID = room.RoomID,
                        ServiceID = serviceId
                    };
                    db.RoomServices.Add(roomService);
                }

                db.SaveChanges(); // Lưu tất cả thay đổi vào cơ sở dữ liệu

                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "TypeName");
            ViewBag.Services = db.Services.ToList(); // Lấy lại danh sách dịch vụ nếu có lỗi
            return View(room);
        }


        [Route("Edit")]
        public IActionResult Edit(string id)
        {
            // Check role
            var roleString = HttpContext.Session.GetString("Role");
            if (Enum.TryParse(roleString, out AccountType role) && role != AccountType.Admin)
            {
                // Not permission
                return RedirectToAction("AccessDenied", "Account");
            }

            if (id == null || db.Rooms == null)
            {
                return NotFound();
            }
            //var room = db.Rooms.Find(id);
            var room = db.Rooms.Include(c => c.Category)
                              .Include(i => i.Images)
                              .Include(s => s.RoomServices)
                              .ThenInclude(rs => rs.Service)// Include Service for RoomService
                              .Include(f => f.RentForms)
                              .FirstOrDefault(r => r.RoomID == id);
            if (room == null)
            {
                return NotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "TypeName", room.CategoryID);
            ViewBag.Services = db.Services.ToList(); // Lấy danh sách tất cả dịch vụ
            ViewBag.SelectedServices = room.RoomServices.Select(rs => rs.ServiceID).ToList(); // Dịch vụ hiện tại của phòng

            return View(room);
        }

        [HttpPost]
        [Route("Edit")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(string id, [Bind("RoomID, CategoryID, Status")] Room room, List<IFormFile> RoomImages, List<string> selectedServices)
        {
            if (id != room.RoomID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // Tìm phòng hiện tại trong database và bao gồm danh sách hình ảnh, dịch vụ liên quan
                    var existingRoom = db.Rooms.Include(r => r.Images)
                                       .Include(r => r.RoomServices)
                                       .FirstOrDefault(r => r.RoomID == id);

                    if (existingRoom == null)
                    {
                        return NotFound();
                    }

                    // Cập nhật thông tin phòng
                    existingRoom.CategoryID = room.CategoryID;
                    existingRoom.Status = room.Status;

                    if(RoomImages != null && RoomImages.Any())
                    {
                        // Thiết lập ImageID cuối cùng, bắt đầu từ 0 nếu không có ảnh nào trong hệ thống
                        var lastImage = db.Images.OrderByDescending(i => i.ImageID).FirstOrDefault();
                        int lastNumber = lastImage != null ? int.Parse(lastImage.ImageID.Substring(3)) : 0;

                        // Thêm mới hoặc cập nhật các ảnh
                        int imageIndex = 0;
                        foreach (var imageFile in RoomImages)
                        {
                            if (imageFile != null && imageFile.Length > 0)
                            {

HotelManagement/HotelManagement/Controllers/HomeBookingController.cs
using HotelManagement.Data;
using HotelManagement.Models;
using HotelManagement.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace HotelManagement.Controllers
{
    public class HomeBookingController : Controller
    {
        private HotelDbContext db;

        public HomeBookingController(HotelDbContext db)
        {
            this.db = db;
        }

        public IActionResult Index(string categoryId, string roomId, DateTime dateCome, DateTime dateGo, int numPeople)
        {
            if (categoryId != null)
            {
                var category = db.Categories.Where(c => c.CategoryID == categoryId).Include(c => c.Rooms).FirstOrDefault();
				ViewBag.Rooms = new SelectList(category.Rooms.Where(r => r.Status == "Vacant").ToList(), "RoomID", "RoomID");
				ViewBag.Category = db.Categories.Where(c => c.CategoryID == categoryId).FirstOrDefault();
            }
            if (roomId != null)
            {
                var room = db.Rooms.Where(r => r.RoomID == roomId).Include(r => r.Category).FirstOrDefault();
                ViewBag.Category = room.Category;
				ViewBag.Room = room;
			}

			ViewBag.Categories = new SelectList(db.Categories.ToList(), "CategoryID", "TypeName");
            
            if (dateCome < DateTime.Now && dateGo < DateTime.Now)
            {
                dateCome = DateTime.Now;
                dateGo = DateTime.Now;
            }

            ViewBag.DateCome = dateCome.ToString("MM/dd/yyyy");
            ViewBag.DateGo = dateGo.ToString("MM/dd/yyyy");
            ViewBag.NumPeople = numPeople;

			return View();
        }

        [HttpPost]
        public IActionResult Book(string rid, BookingViewModel model)
		{
            var rooms = db.Rooms.Include(r => r.Category).ToList();
            Room room = null;
			if (rid != null)
			{
				room = rooms.FirstOrDefault(r => r.RoomID == rid);
				ViewBag.Category = room.Category;
				ViewBag.Room = room;
			}

			// Generate Customer ID
			string customerID = "";
			string bookingID = "";
            string rentFormID = GenerateID("RF");

			while (true)
			{
				customerID = GenerateID("CUS");

				if (!db.Customers.Any(c => c.CustomerID == customerID))
				{
					model.Customer.CustomerID = customerID;
					break;
				}

			}

			while (true)
			{
				bookingID = GenerateID("BK");

				if (!db.Bookings.Any(b => b.BookingID == bookingID))
				{
					model.Booking.BookingID = bookingID;

                    // Remove state 
                    ModelState.Remove("Booking.BookingID");
					break;
				}
			}

            // Check valid 
			if (ModelState.IsValid)
            {
                try
                {
					db.Add(new Booking
					{
						BookingID = bookingID,
						CustomerID = customerID,
						DateCome = model.Booking.DateCome,
						DateGo = model.Booking.DateGo,
						NumberPeople = model.Booking.NumberPeople,
					});
					db.Add(new BookingDetail
                    {
                        BookingID = bookingID,
                        CategoryID = room.CategoryID,
                        NumberRoom = 1
                    });
                    db.Add(new RentForm
                    {
                        RentFormID = rentFormID,
                        BookingID = bookingID,
                        StaffID = "S0001",
                        RoomID = rid,
                        CustomerID = customerID,
                        DateCreate = DateTime.Now,
                        DateCheckIn = model.Booking.DateCome,
                        DateCheckOut = model.Booking.DateGo,
                        Sale = 0
                    });

                    db.Customers.Add(model.Customer);
                    db.SaveChanges();

                    return RedirectToAction("Index", "Home");
                }
                catch (Exception ex)
                {
                    return Content(ex.Message);
                }
            }

            ViewBag.Categories = new SelectList(db.Categories.ToList(), "CategoryID", "TypeName");

            return View("Index");
        }

        /// <summary>
        /// Generate Random ID
        /// </summary>
        /// <param name="idBase"></param>
        /// <returns></returns>
        private string GenerateID(string idBase)
        {
            string id = "";
            switch (idBase)
            {
                case "CUS":
					id = idBase + new Random().NextInt64(100000).ToString("d5");
                    break;
                case "BK":
					id = idBase + new Random().NextInt64(100000).ToString("d5");
                    break;
                case "RF":
                    id = idBase + new Random().NextInt64(100000).ToString("d5");
                    break;
            }

            return id;
        }
	}
}

HotelManagement/HotelManagement/Controllers/RoomController.cs
using HotelManagement.Data;
using HotelManagement.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace HotelManagement.Controllers
{
    public class RoomController : Controller
    {
        private HotelDbContext db;

        public RoomController(HotelDbContext db)
        {
            this.db = db;
        }

        public IActionResult Index(int page = 1)
        {
          

            //ViewBag.Categories = db.Categories.Include(c => c.Rooms).ToList();
            ViewBag.Services = db.Services.ToList();

            int NoOfRecordPerPage = 6;
            int totalRoom = db.Categories.Count();
            int NoOfPages = (int)Math.Ceiling((double)totalRoom/ NoOfRecordPerPage);
            int NoOfRecordToSkip = (page - 1) * NoOfRecordPerPage;

            ViewBag.Page = page;
            ViewBag.NoOfPages = NoOfPages;

            var categories = db.Categories.Include(c => c.Rooms)
                                          .Skip(NoOfRecordToSkip)
                                          .Take(NoOfRecordPerPage)
                                          .ToList();
            ViewBag.Categories = categories;
            return View();
        }
        public IActionResult Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = db.Categories.Where(c => c.CategoryID == id).Include(c => c.Rooms).FirstOrDefault();
            ViewBag.Services = db.Services.ToList();
            ViewBag.Rates = db.Rates.ToList();
            return View(room);
        }

        [HttpGet]
        public IActionResult RoomAvailable(string id, DateTime dateCome, DateTime dateGo, int numPeople)
        {
            if (dateCome >= dateGo)
            {
                TempData["Error"] = "Date Check-in/ Check-out is not valid!";

                return RedirectToAction(nameof(Index), "Home");
            }

            var unavailableRoomIds = db.RentForms
                .Where(r => (dateCome < r.DateCheckOut && dateGo > r.DateCheckIn))
                .Select(r => r.RoomID)
                .ToList();

            var availableRooms = db.Rooms
                .Where(r => !unavailableRoomIds.Contains(r.RoomID) && r.Status == "Vacant")
                .Include(r => r.Category)
                .Include(r => r.Images)
                .ToList();

            if (!string.IsNullOrEmpty(id))
            {
                availableRooms = availableRooms.Where(r => r.CategoryID == id).ToList();
            }
            ViewBag.DateCome = dateCome;
            ViewBag.DateGo = dateGo;
            ViewBag.Rooms = availableRooms;
            ViewBag.CategoryID = id;
            ViewBag.NumPeople = numPeople;

            return View();
        }
    }
}

HotelManagement/HotelManagement/Views/Room/Details.cshtml
@model HotelManagement.Models.Category
@{
	ViewData["Tittle"] = "Room Details";
}
 
<!-- Breadcrumb Section Begin -->
<div class="breadcrumb-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-text">
                    <h2>Our Rooms</h2>
                    <div class="bt-option">
                        <a asp-controller="Home" asp-action="Index">Home</a>
                        <a asp-controller="Room" asp-action="Index">Rooms</a>
                        <span>Room Details</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb Section End -->
<!-- Room Details Section Begin -->
<section class="room-details-section spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="room-details-item">
                    <img src="~/TemplateLayout/MainWebPage/img/room/room-details.jpg" alt="">
                    <div class="rd-text">
                        <div class="rd-title">
                            <h3>@Model.TypeName</h3>
                            <div class="rdt-right">
                                <div class="rating">
                                    <i class="icon_star"></i>
                                    <i class="icon_star"></i>
                                    <i class="icon_star"></i>
                                    <i class="icon_star"></i>
                                    <i class="icon_star-half_alt"></i>
                                </div>
                                <a asp-controller="HomeBooking" asp-action="Index" asp-route-categoryId="@Model.CategoryID">Booking Now</a>
                            </div>
                        </div>
                        <h2>@string.Format("{0:N0} VND", Model.Price)<span>/Pernight</span></h2>
                        <table>
                            <tbody>
                                <tr>
                                    <td class="r-o">Size:</td>
                                    <td>@Model.Capacity</td>
                                </tr>
                                <tr>
                                    <td class="r-o">Capacity:</td>
                                    @{
                                        int capacity = int.Parse(Model.CategoryID.ToString().Substring(Model.CategoryID.ToString().Length - 2));
                                    }
                                    <td>
                                        Max person @(capacity + 1)
                                    </td>
                                </tr>
                                <tr>
                                    <td class="r-o">Services:</td>
                                    <td>Wifi, Television, Bathroom,...</td>
                                </tr>
                            </tbody>
                        </table>
                        <p class="f-para">
                            Motorhome or Trailer that is the question for you. Here are some of the
                            advantages and disadvantages of both, so you will be confident when purchasing an RV.
                            When comparing Rvs, a motorhome or a travel trailer, should you buy a motorhome or fifth
                            wheeler? The advantages and disadvantages of both are studied so that you can make your
                            choice wisely when purchasing an RV. Possessing a motorhome or fifth wheel is an
                            achievement of a lifetime. It can be similar to sojourning with your residence as you
                            search the various sites of our great land, America.
                        </p>
                        <p>
                            The two commonly known recreational vehicle classes are the motorized and towable.
                            Towable rvs are the travel trailers and the fifth wheel. The rv travel trailer or fifth
                            wheel has the attraction of getting towed by a pickup or a car, thus giving the
                            adaptability of possessing transportation for you when you are parked at your campsite.
                        </p>
                    </div>
                </div>
                <div class="rd-reviews">
                    <h4>Reviews</h4>
                    @foreach(var rate in ViewBag.Rates)
                    {
                        <div class="review-item">
                            <div class="ri-pic">
                                <img src="~/img/user.png" alt="">
                            </div>
                            <div class="ri-text">
                                <span>@String.Format("{0:MMMM dd, yyyy}", rate.DateCreate)</span>
                                <div class="rating">
                                    <i class="icon_star"></i>
                                    <i class="icon_star"></i>
                                    <i class="icon_star"></i>
                                    <i class="icon_star"></i>
                                    <i class="icon_star-half_alt"></i>
                                </div>
                                <h5>@rate.Username</h5>
                                <p>
                                    @rate.Message
                                </p>
                            </div>
                        </div>
                    }
                </div>
                <div class="review-add">
                    <h4>Add Review</h4>
                    <form action="#" class="ra-form">
                        <div class="row">
                            <div class="col-lg-6">
                                <input type="text" placeholder="Name*">
                            </div>
                            <div class="col-lg-6">
                                <input type="text" placeholder="Email*">
                            </div>
                            <div class="col-lg-12">
                                <div>
                                    <h5>You Rating:</h5>
                                    <div class="rating">
                                        <i class="icon_star"></i>
                                        <i class="icon_star"></i>
                                        <i class="icon_star"></i>
                                        <i class="icon_star"></i>
                                        <i class="icon_star-half_alt"></i>
                                    </div>
                                </div>
                                <textarea placeholder="Your Review"></textarea>
                                <button type="submit">Submit Now</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="room-booking">
                    <h3>Your Reservation</h3>
                    <form asp-controller="Room" asp-action="RoomAvailable" asp-route-id="@Model.CategoryID" method="get">
                        <div class="check-date">
                            <label for="date-in">Check In:</label>
                            <input type="date" name="dateCome" required>
                        </div>
                        <div class="check-date">
                            <label for="date-out">Check Out:</label>
                            <input type="date" name="dateGo" required>
                        </div>
                        <button type="submit">Check Availability</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Room Details Section End -->

HotelManagement/HotelManagement/Views/Room/RoomAvailable.cshtml
@{
    ViewData["Tittle"] = "Room Available";
}

<!-- Breadcrumb Section Begin -->
<div class="breadcrumb-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-text">
                    <h2>Rooms Available</h2>
                    <div class="bt-option">
                        <a asp-controller="Home" asp-action="Index">Home</a>
                        <span>Rooms Available</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb Section End -->

@{
    if (ViewBag.Rooms.Count <= 0)
    {
        <div class="container-fluid d-flex flex-column align-items-center justify-content-center">
            <h3>Oops! No Available Room!</h3>
            <a type="button" class="btn btn-lg btn-outline-success mt-5" asp-controller="Room" asp-action="Index">Back</a>
        </div>
    }
}
<section class="rooms-section spad">
<div class="container">
    <div class="row">
        @foreach (var room in ViewBag.Rooms)
        {
            string imageUrl = "";
            foreach (var image in room.Images) 
            {
                imageUrl = image.ImageUrl;
                break;
            }
            <div class="col-lg-4 col-md-6">
                <div class="room-item">
                    <img src="@imageUrl" alt="Room Image" style="height:220px">
                    <div class="ri-text">
                        <h4>@room.Category.TypeName</h4>
                        <h3>@room.RoomID</h3>
                        <a asp-controller="HomeBooking" asp-action="Index" 
                                    asp-route-categoryId="@ViewBag.CategoryID" 
                                    asp-route-roomId="@room.RoomID"
                                    asp-route-dateCome="@ViewBag.DateCome"
                                    asp-route-dateGo="@ViewBag.DateGo"
                                    asp-route-numPeople="@ViewBag.NumPeople"
                                    class="primary-btn">
                                    Book
                        </a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
</section>